use utoipa::OpenApi;

use crate::error;
use crate::handlers;
use crate::models;
use crate::sse;

#[derive(OpenApi)]
#[openapi(
    paths(
        handlers::health::health_check,
        handlers::health::liveness,
        handlers::health::readiness,
        handlers::auth::register,
        handlers::auth::login,
        handlers::auth::logout,
        handlers::auth::me,
        handlers::tasks::list_tasks,
        handlers::tasks::create_task,
        handlers::tasks::get_task,
        handlers::tasks::update_task,
        handlers::tasks::delete_task,
        handlers::projects::list_projects,
        handlers::projects::create_project,
        handlers::projects::get_project,
        handlers::projects::update_project,
        handlers::projects::delete_project,
        handlers::project_members::list_members,
        handlers::project_members::add_member,
        handlers::project_members::get_member,
        handlers::project_members::update_member,
        handlers::project_members::remove_member,
        handlers::agent_sessions::create_agent_session,
        handlers::agent_sessions::list_agent_sessions,
        handlers::agent_sessions::get_agent_session,
        handlers::agent_sessions::update_agent_session,
        handlers::agent_sessions::start_agent_session,
        handlers::agent_sessions::stop_agent_session,
        handlers::agent_sessions::pause_agent_session,
        handlers::agent_sessions::resume_agent_session,
        handlers::agent_sessions::get_agent_session_outputs,
        handlers::agent_sessions::restart_agent_session,
        handlers::users::search_users,
        handlers::task_comments::create_comment,
        handlers::task_comments::list_comments,
        handlers::task_comments::update_comment,
        handlers::task_comments::delete_comment,
        handlers::project_messages::list_messages,
        handlers::project_messages::create_message,
        handlers::project_messages::delete_message,
        handlers::worktrees::list_worktrees,
        handlers::worktrees::create_worktree,
        handlers::worktrees::get_worktree,
        handlers::worktrees::delete_worktree,
        handlers::github_links::create_github_link,
        handlers::github_links::get_github_link,
        handlers::github_links::delete_github_link,
        handlers::github_links::get_github_link_status,
        handlers::github_links::sync_github_link,
        handlers::pull_requests::list_pull_requests,
        handlers::previews::create_preview,
        handlers::previews::list_previews,
        handlers::previews::get_preview,
        handlers::previews::delete_preview,
        handlers::previews::start_preview,
        handlers::previews::stop_preview,
        handlers::previews::restart_preview,
        handlers::webhooks::github_webhook,
    ),
    components(schemas(
        models::task::Task,
        models::task::TaskStatus,
        models::task::TaskPriority,
        models::task::CreateTaskRequest,
        models::task::UpdateTaskRequest,
        models::project::Project,
        models::project::CreateProjectRequest,
        models::project::UpdateProjectRequest,
        models::project::ProjectMember,
        models::project::MemberRole,
        models::project::AddMemberRequest,
        models::project::UpdateMemberRequest,
        models::user::User,
        models::user::RegisterRequest,
        models::user::LoginRequest,
        models::user::AuthResponse,
        models::agent_session::AgentSession,
        models::agent_session::AgentType,
        models::agent_session::AgentSessionStatus,
        models::agent_session::CreateAgentSessionRequest,
        models::agent_session::UpdateAgentSessionRequest,
        models::agent_session::StartAgentSessionRequest,
        models::agent_session::StartAgentSessionResponse,
        models::agent_session_output::AgentSessionOutput,
        sse::event::SseEvent,
        handlers::worktrees::WorktreeResponse,
        handlers::worktrees::CreateWorktreeRequest,
        models::pagination::PaginatedResponse<models::task::Task>,
        models::pagination::PaginatedResponse<models::project::Project>,
        handlers::health::HealthResponse,
        handlers::health::LivenessResponse,
        handlers::health::ReadinessResponse,
        models::task_comment::TaskComment,
        models::task_comment::CreateCommentRequest,
        models::task_comment::UpdateCommentRequest,
        models::project_message::ProjectMessage,
        models::project_message::CreateMessageRequest,
        models::github::GitHubLink,
        models::github::CreateGitHubLinkRequest,
        models::github::GitHubLinkStatus,
        models::github::GitHubPullRequest,
        models::github::PrState,
        models::docker_preview::DockerPreview,
        models::docker_preview::PreviewStatus,
        models::docker_preview::CreatePreviewRequest,
        error::ErrorResponse,
        error::ErrorDetail,
        error::ErrorCode,
    )),
    tags(
        (name = "health", description = "Health check"),
        (name = "auth", description = "Authentication"),
        (name = "tasks", description = "Task management"),
        (name = "projects", description = "Project management"),
        (name = "project-members", description = "Project member management"),
        (name = "agent-sessions", description = "Agent session management"),
        (name = "users", description = "User management"),
        (name = "task-comments", description = "Task comment management"),
        (name = "project-messages", description = "Project chat messages"),
        (name = "worktrees", description = "Git worktree management"),
        (name = "github-links", description = "GitHub link management"),
        (name = "pull-requests", description = "Pull request management"),
        (name = "previews", description = "Docker preview management"),
        (name = "webhooks", description = "Webhook endpoints"),
    ),
    info(
        title = "Gantry Board API",
        version = "0.1.0",
        description = "AI Agent Orchestration Kanban Board API",
        license(name = "Apache-2.0", identifier = "Apache-2.0")
    )
)]
pub struct ApiDoc;
